# This is a basic workflow to help you get started with Actions

name: DefaultWorkflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      env: 
        GPG_KEY: ${{ secrets.GPG_KEY }}
      run: |
        echo -e "$GPG_KEY" > key.asc
        gpg --import key.asc
        gpg --list-secret-keys --keyid-format LONG

    - name: Run something else
      run: |
        git config user.signingkey E35A02C55FBCA4CE
        git config user.email "user@github-noreply.com"
        git config user.name "Hub User"
        git tag -s -m "CI tagged" v0.2.0
        git push origin master

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
