# This is a basic workflow to help you get started with Actions

name: DefaultWorkflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:

  pull_request:
    branches: [ '!master' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup GIt
      env: 
        GPG_KEY: ${{ secrets.GPG_KEY }}
      run: |
        echo -e "$GPG_KEY" > key.asc
        gpg --import key.asc
        git config user.signingkey ${{ secrets.GPG_KEY_ID }}
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config user.name "${{ secrets.GIT_USER}}"
        git tag -s -m "CI tagged" v0.2.0
        git push origin --tags

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
