name: "smoke-screen-tests"
on:
  push:
    branches-ignore: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: echo Test Complete
    - uses: LouisBrunner/checks-action@v0.1.0
      if: always()
      with:
        token: ${{ secrets.AUTH_TOKEN }}
        name: Tests Complete
        conclusion: success